name: OWASP ZAP Scan
on:
    push:
      branches:
        - master
    pull_request:
      types: [opened, synchronize, reopened]
    workflow_run:
        workflows: ['SCA analysis - Snyk']
        types:
            - completed

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'